### ISSUE TITLE
Could not load `sumocfg` files.

### ISSUE THREAD

**Issue by Ezharjan** [M-Colley/pedsumo#1]
0. First, thanks for your nice work.

1. When I run `main.py`, it outputs error:
```
(pedsumo) alex@fst-computer:~/Documents/pedsumo/SumoWithAVs$ python main.py 
xml2csvSWA: Could not find xml2csv.py file. Looked in path: /usr/bin/sumo/tools/xml/xml2csv.py
 Retrying in 1 seconds
Error: On processing option '--statistic-output':
 No option with the name 'statistic-output' exists.
Error: The parameter '../simulation-results/Wildau-avd0.500-ed0.200-dss0.000-20240114-131207/stats.xml' is not allowed in this context.
 Switch or parameter name expected.
Error: On processing option '--person-summary-output':
 No option with the name 'person-summary-output' exists.
Error: The parameter '../simulation-results/Wildau-avd0.500-ed0.200-dss0.000-20240114-131207/personsummary.xml' is not allowed in this context.
 Switch or parameter name expected.
Error: Could not parse commandline options.
Quitting (on error).
```

I didn't install SUMO through its source but directly from `apt`.

It seems that the code is searching a file named `xml2csv.py` which might be in the official source code of SUMO.
Does that mean that I have to build SUMO from source? or just simply put `xml2csv.py` from SUMO's repository to someplace and run again?

2. After I set the correct path for SUMO and now it can find `xml2csv.py`. But on running the code again, it still outputs the following error:

```
(pedsumo) alex@fst-computer:~/Documents/pedsumo/SumoWithAVs$ export SUMO_HOME=/usr/share/sumo/
(pedsumo) alex@fst-computer:~/Documents/pedsumo/SumoWithAVs$ python main.py 
 Retrying in 1 seconds
Error: On processing option '--statistic-output':
 No option with the name 'statistic-output' exists.
Error: The parameter '../simulation-results/Ingolstadt-avd0.500-ed0.200-dss0.000-20240114-131833/stats.xml' is not allowed in this context.
 Switch or parameter name expected.
Error: On processing option '--person-summary-output':
 No option with the name 'person-summary-output' exists.
Error: The parameter '../simulation-results/Ingolstadt-avd0.500-ed0.200-dss0.000-20240114-131833/personsummary.xml' is not allowed in this context.
 Switch or parameter name expected.
Error: Could not parse commandline options.
Quitting (on error).
/home/alex/anaconda3/envs/pedsumo/lib/python3.11/site-packages/traci/main.py:154: UserWarning: Could not connect to TraCI server using port 59099 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +
 Retrying in 1 seconds
```

What should I do to fix it?

Thanks!

**Comment by M-Colley** [comment]
Hey there and thank you for your interest in this project!

You are correct, the source code looks for this python file. 

This is the relevant code in the `xml2csvSWA.py` file:


```
# automatically adjusts xml2csvPath to your operating system
path_set_successful: bool = True
if automaticPathAdjust:
    try:
        string_to_xml2csv_per_os = os.path.join("tools", "xml", "xml2csv.py")
        xml2csvPath = os.path.join(os.getenv("SUMO_HOME"), string_to_xml2csv_per_os)
    except:
        path_set_successful = False
        print("xml2csvSWA: Could not find system path to SUMO_HOME.")

if not os.path.exists(xml2csvPath):
    path_set_successful = False
    print("xml2csvSWA: Could not find xml2csv.py file. Looked in path: " + xml2csvPath)
```


Which SUMO version do you have?
Can you try and locate the `xml2csv.py` file? while we have tried our code on MAC and Windows, you might have a different setup..

**Comment by Ezharjan** [comment]
> Hey there and thank you for your interest in this project!
> 
> You are correct, the source code looks for this python file.
> 
> This is the relevant code in the `xml2csvSWA.py` file:
> 
> ```
> # automatically adjusts xml2csvPath to your operating system
> path_set_successful: bool = True
> if automaticPathAdjust:
>     try:
>         string_to_xml2csv_per_os = os.path.join("tools", "xml", "xml2csv.py")
>         xml2csvPath = os.path.join(os.getenv("SUMO_HOME"), string_to_xml2csv_per_os)
>     except:
>         path_set_successful = False
>         print("xml2csvSWA: Could not find system path to SUMO_HOME.")
> 
> if not os.path.exists(xml2csvPath):
>     path_set_successful = False
>     print("xml2csvSWA: Could not find xml2csv.py file. Looked in path: " + xml2csvPath)
> ```
> 
> Which SUMO version do you have? Can you try and locate the `xml2csv.py` file? while we have tried our code on MAC and Windows, you might have a different setup..

Thanks for you response!
Yes, I'm using Linux `Ubuntu 20.04 LTS` with the SUMO version of `Eclipse SUMO Version 1.4.0 | Build features: x86_64-pc-linux-gnu GDAL GUI`.
I'll try again somedays later on my `Windows 11` platform.

**Comment by M-Colley** [comment]
Thanks for clarifying. I believe the SUMO version is the cause of the error. I think the conversion was only added much later. We have tested (and only support) versions 1.17.0, 1.18.0, and 1.19.0.

Please try it with those and, in the best case, in the newest version.

Kind regards

**Comment by Ezharjan** [comment]
> Thanks for clarifying. I believe the SUMO version is the cause of the error. I think the conversion was only added much later. We have tested (and only support) versions 1.17.0, 1.18.0, and 1.19.0.
> 
> Please try it with those and, in the best case, in the newest version.
> 
> Kind regards

Thanks!

I have updated my SUMO to `1.19.0` using the following commands:
```bash
sudo add-apt-repository ppa:sumo/stable
sudo apt-get update
sudo apt-get install sumo sumo-tools sumo-doc
```
And now the sumo version is:
```
Eclipse SUMO sumo Version 1.19.0
 Build features: Linux-5.4.0-164-generic x86_64 GNU 9.4.0 Release FMI Proj GUI Intl SWIG GDAL GL2PS Eigen
 Copyright (C) 2001-2023 German Aerospace Center (DLR) and others; https://sumo.dlr.de

Eclipse SUMO sumo Version 1.19.0 is part of SUMO.
This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
This program may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License 2.0 are satisfied: GNU General Public License, version 2
or later which is available at
https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
```
<br>

After reinstalling all the requirements and rerunning the command `python main.py` in `SumoWithAVs` folder, the following error occurs:
```
(pedsumo) alex@fst-computer:~/Documents/PedSUMO/SumoWithAVs$ python main.py 
 Retrying in 1 seconds
Error: invalid document structure
Error:  (At line/column 2/1).
Error: Could not load configuration '../resources/wildau/randomTrips/output_configuration_randomTrips.sumocfg'.
Quitting (on error).
/home/alex/anaconda3/envs/pedsumo/lib/python3.11/site-packages/traci/main.py:154: UserWarning: Could not connect to TraCI server using port 44765 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +
 Retrying in 1 seconds
Error: invalid document structure
Error:  (At line/column 2/1).
Error: Could not load configuration '../resources/wildau/randomTrips/output_configuration_randomTrips.sumocfg'.
Quitting (on error).
```
It seems that you didn't put the correct content that is loadable by the program inside `output_configuration_randomTrips.sumocfg`. The content inside one of the `.sumocfg` files is:
```
(pedsumo) alex@fst-computer:~/Documents/PedSUMO/resources/bologna$ cat run.sumocfg 
version https://git-lfs.github.com/spec/v1
oid sha256:691c3d2e863de9efa02035f5c83f962ed67be77871e85eb9cde3c5e284207999
size 868
```
 
Does this mean that I have to clone the repository only via "gitlab-mi.informatik.uni-ulm.de:ehmi/sumo-se-2022.git" ? 
**Are there any ways do clone it directly through Github without missing the correct content inside `.sumocfg` files?**

**Comment by M-Colley** [comment]
Thank you for bringing this up! It does seem like the wrong files (or not the full files) were uploaded here. I will resolve this in my next commit :)

**Comment by M-Colley** [comment]
So the problem is with GIT LFS and the quota per project (1GB per month). Therefore, I have created a Google Drive link to download the `resources` directory.

The link is: https://drive.google.com/file/d/1QdxX8_j1YggWxMeIVQcxMbVKmSrN1a92/view?usp=drive_link

Just replace the resources folder with this folder.

Kind regards

**Comment by Ezharjan** [comment]
Thanks!
