### ISSUE TITLE
name 'gui' is not defined

### ISSUE THREAD

**Issue by nchuly** [M-Colley/pedsumo#2]
hi, thanks for your great work!
when running `python main.py` with `guiOn = True` in `config.py`, i encouter an error "name 'gui' is not defined", could you please help me?

**Comment by nchuly** [comment]
sorry. my fault

**Comment by M-Colley** [comment]
Hey there and thank you for using `pedsumo`. I have updated the requirements and fixed a missing import. It should now work.

Kind regards

**Comment by nchuly** [comment]
thanks :)
